apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-demo-deployment
  namespace: arch
spec:
  replicas: 1 #只运行一个nginx
  template:
    metadata:
      labels: #必须匹配之前的spec.selector
        app: spring-boot-demo #pod副本拥有此标签，对用RC的selector
    spec:
      containers: #pod内容器定义
      - name: spring-boot-demo #容器的名称
        image: 192.168.1.207/architecture/spring-boot-demo:1.0.0 #容器对应的docker image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-svc
  namespace: arch
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8555
  selector: #选择器
    app: spring-boot-demo #符合目标的pod拥有此标签